### PR TITLE
AndroidThings Set-ups

### PR DESCRIPTION
**Pull request by schorliee**

### CODE REVIEW

**Comment by lbb** [comment]
PTAL

**Comment by lbb** [comment]
To fulfill the definition-of-done, we run the connected Checks. And tested it against the Android Things kit.

**Review by ghost — DISMISSED** [review]
I am missing the unit test.

**Comment by xiamaz** [comment]
Is it possible to add a dummy unittest against android things, or is it not possible to explicitly test against android things?

**Comment by ghost** [comment]
I have never done this but I think it should be possible with [instrumented unit tests](https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests). Question is just whether we really want that because they are much slower than [local unit tests](https://developer.android.com/training/testing/unit-testing/local-unit-tests) and we won't have them on each team member's computer. To be honest, I am not sure whether it makes sense to have a unit test for this but the professor complained last time that we were not respecting our definition of done and I felt quite pressured that we must include unit tests in our definition of done.

**Comment by xiamaz** [comment]
This is definitely reasonable, since it is already extremely hard to catch errors happening on hardware platforms aside from our own devices.

We definitely do not need to test every detail with instrumented tests, but it would be reasonable to have a few for our core components.

**Comment by lbb** [comment]
I can see that it makes sense in a larger setup to have a test in place for the correct build flavors. The only thing we would get out of a test is if it the target platform matches the build flavor. If you try to push the wrong target to the device it will give an error, that the platform is not compatible. I feel the unit test is an overengineered solution to this problem.

**Review by xiamaz — APPROVED** [review]

**Pull request merged**
