### PR TITLE
delete unused recording code

### PR DESCRIPTION
**Pull request by abdulmth**

### CODE REVIEW

**Review by xiamaz — CHANGES_REQUESTED** [review]
Looks good, but could you undo deleting the fakeinputlib.jar? This is part of a different component. We can clean up that part in a different PR.

**Comment by abdulmth** [comment]
@xiamaz I actually didn't delete it intentionally, could it be deleted after a fresh build?

**Comment by ghost** [comment]
@abdulmth you can get it back with

    $ git checkout '<last-commit-where-it-still-existed>' -- '<filename>'

**Comment by abdulmth** [comment]
@zerik @xiamaz I restored the deleted jar.

**Review by ghost — APPROVED** [review]

**Review by lvap — APPROVED** [review]

**Review by xiamaz — APPROVED** [review]

**Pull request merged**
