### PR TITLE
User Story #8: Automated tagging

### PR DESCRIPTION
**Pull request by ghost**
Both, server and client app, now have an additional activity called *BuildInfoActivity* which displays the name of the newest git tag, the committer date of the current commit, the date of the build and the name of the package.

### CODE REVIEW

**Comment by lbb** [comment]
@zerik I'll take a look at this.
/cc @abdulmth @alejo096 @xiamaz PTAL

**Review by xiamaz — DISMISSED** [review]

**Comment by ghost** [comment]
I am still waiting to merge this because Charlie reported that something was not working corretly in this feature. Also, I do not want to merge anything as long as the master branch is not running.

**Comment by schorliee** [comment]
I just have some problems executing the code as a Windows User. However, it worked on Linux.

**Review by schorliee — APPROVED** [review]
Works on my Windows now as well.

**Pull request merged**
